# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714d74471405d5ec921e2390af72c2d51aad40060faffe96e62b4e5a18a230460d563bbdf148ff47ce6dbd1afad0c2704e87f53670f5f7c75fa1697142f7e2b0

test:
  secret_key_base: 0b80e0e31d6b896ff669a0470dde4b8a488290a09c1fc22e3bcdd8eaffced941dc5487933bcec473307a52770252b922a05ee2af1c19b973eb4d7a91819ab7a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
